### ISSUE TITLE
Вопрос по ecs-reactive

### ISSUE THREAD

**Issue by Krakean** [Leopotam/ecs-reactive#1]
Здравствуй, дорогой автор
Скажи пожалуйста, в чем смысл ecs-reactive как дополнение к твоему основному ecs? 
Что дает, какие плюсы/минусы, и в каких случаях предпочтительно использовать?
Просто не знаю, нужен мне ecs-reactive или нет, пока только изучаю твой ecs, и хотелось бы понять для чего ecs-reactive вообще нужен.
Спасибо за внимание

**Comment by Leopotam** [comment]
По сути это поведение, похожее на реактивные системы в Entitas - вот и весь смысл. Почему-то оно считается удобным и полезным, что как по мне - очень странно. По производительности - есть накладные расходы в плане локального списка измененных сущностей, которые нужно обработать реактивной системой - этот список нужно хранить (расходы на память), набивать данными (подписка на события фильтра) и очищать после процессинга. По скорости оно примерно такое же, как в Entitas:
![](https://habrastorage.org/webt/vk/cs/rz/vkcsrzdktgjhdoh5hrdjegnwvo0.jpeg)

**Comment by Leopotam** [comment]
@Krakean вопрос исчерпан?

**Comment by Leopotam** [comment]
Если появятся новые детали по вопросу - открою снова.
